schedule:
  start_time: null
  end_time: null
  duration: "00:01"

out_path: ./output

camera_system:
  cameras:
    ptz1:
      name: Avonic_CM93_NDI
      enable: True
      ip: 192.168.33.101
      visca_port: 52381
      src: ndi
      fps: 30
      presets:
        left: [65286, 65158]
        center: [0x1000c, 0xfe64]
        right: [65777, 65158]
      camera_params: null
      speed: 0x04
      stream: False
    ptz2:
      name: Avonic_CM93_NDI
      enable: True
      ip: 192.168.33.102
      visca_port: 52381
      src: ndi
      fps: 30
      presets:
        left: [65051, 65149]
        center: [0x1002a, 0xfe4d]
        right: [66018, 65143]
      camera_params: null
      speed: 0x04
    pano:
      name: Vivotek-MS9321-EHV-V2
      enable: True
      ip: 192.168.33.103
      #src: /home/bvsc-oxit/Videos/cropped.mp4
      src: rtsp://192.168.33.103:554/media2/stream.sdp?profile=Profile200
      frame_size: [4096, 1484]
      crop: [380, 265, 1230, 4096] # (top_y, top_x, bottom_y, bottom_x)
      fps: 5
      camera_params: null #./camera_params/bvsc/pano_params_bvsc.npy
      distort: "./camera_params/bvsc/remap_4096x1484_fov115.npz"
      save: True
  
  pano_onnx: ./models/rtdetrv2_pano.onnx
  track_threshold: 1.0
  
bev:
  points:
    world: [[-25, 10], [-25,8.75], [-25,6.25], [-25,3.75], [-25,1.25], [-25,-1.25], [-25,-3.75], [-25,-6.75], [-25,-8.75], [-25,-10], [0,10], [0,-10], [25,10], [25,8.75], [25,6.25], [25,1.25], [25,-1.25], [25,-3.75], [25,-6.25], [25,-8.75], [25,-10]]
    image: [[939, 99], [904,128], [842,178], [773,235], [693,300], [601,375], [467,465], [339,571], [187,696], [80,787], [1885,52], [1885,749], [2849,30], [2885,56], [2951,104], [3113,219], [3214,291], [3347,377], [3487,476], [3658,597], [3778,685]]
  court_size: [25, 20]