schedule:
  start_time: null
  end_time: null
  duration: "00:01"

out_path: ./output

camera_system:

  cameras:
    ptz1:
      name: Avonic_CM93_NDI
      enable: True
      ip: 172.17.0.212
      visca_port: 52381
      src: ndi
      fps: 25
      presets:
        left: [65009, 65299]
        center: [0x1000c, 0xfe64]
        right: [66020, 65297]
      camera_params: null
      speed: 0x04
      stream: True
    ptz2:
      name: Avonic_CM93_NDI
      enable: True
      ip: 172.17.0.214
      visca_port: 52381
      src: ndi
      fps: 25
      presets:
        left: [66090, 65324]
        center: [0x1002a, 0xfe4d]
        right: [65076, 65324]
      camera_params: null
      speed: 0x04
    pano:
      name: Vivotek-MS9321-EHV-V2
      enable: True
      ip: 172.17.0.213
      # src: rtsp
      src: rtsp://172.17.0.213/media2/stream.sdp?profile=Profile200
      frame_size: [4096, 1484]
      crop: [1, 1, 1484, 4096] # (top_y, top_x, bottom_y, bottom_x)
      fps: 5
      camera_params: null #./camera_params/komjadi/camera_params_komjadi.npy 
      distort: "./camera_params/komjadi/remap_4096x1484_fov125.npz"
      save: True

  pano_onnx: ./models/rtdetrv2_pano.onnx
  track_threshold: 2.0
  
bev:
  points:
    world: [[-25, 10], [-25, 8.75],[-25, 6.25],[-25, 3.75],[-25, 1.25],[-25, -1.25],[-25, -3.75],[-25, -6.75],[-25, -8.75],[-25,-10], [0,10], [0,-10],[25, 10], [25, 8.75],[25, 6.25],[25, 3.75],[25, 1.25],[25, -1.25],[25, -3.75] ]
    image: [[1351, 534], [1304,552], [1228,580], [1138,612], [1015,650], [882,696], [718,753], [507,827], [233,926], [1,1012], [2209,517], [2208,1127], [3135,492], [3192,510], [3284,538], [3393,571], [3528,609], [3695,657], [3912,721]]
  court_size: [25, 20]
