schedule:
  start_time: null
  end_time: null
  duration: "00:01"

out_path: ./output

camera_system:

  cameras:
    ptz1:
      name: Avonic_CM93_NDI
      enable: True
      ip: 172.17.0.212
      visca_port: 52381
      src: ndi
      fps: 30
      presets:
        left: [65009, 65299]
        center: [0x1000c, 0xfe64]
        right: [66020, 65297]
      camera_params: null
      speed: 0x04
      stream: False
    ptz2:
      name: Avonic_CM93_NDI
      enable: True
      ip: 172.17.0.214
      visca_port: 52381
      src: ndi
      fps: 30
      presets:
        left: [66090, 65324]
        center: [0x1002a, 0xfe4d]
        right: [65076, 65324]
      camera_params: null
      speed: 0x04
    pano:
      name: Vivotek-MS9321-EHV-V2
      enable: True
      ip: 172.17.0.213
      # src: rtsp
      src: rtsp://172.17.0.213/media2/stream.sdp?profile=Profile200
      frame_size: [4094, 720]
      crop: [450, 0, 1170, 4094] # (top_y, top_x, bottom_y, bottom_x)
      fps: 5
      camera_params: null #./camera_params/komjadi/camera_params_komjadi.npy 
      distort: "./camera_params/komjadi/remap_4096x1484_fov125.npz"
      save: False

  pano_onnx: ./models/rtdetrv2_pano.onnx
  track_threshold: 2.0
  
bev:
  points:
    world: [[-25, 10], [-25, 8.75],[-25, 6.25],[-25, 3.75],[-25, 1.25],[-25, -1.25],[-25, -3.75],[-25, -6.75],[-25, -8.75],[-25,-10], [0,10], [0,-10],[25, 10], [25, 8.75],[25, 6.25],[25, 3.75],[25, 1.25],[25, -1.25],[25, -3.75] ]
    image: [[1351, 85], [1304,103], [1228,130], [1138,163], [1015,201], [882,248], [718,306], [507,379], [233,477], [1,563], [2209,67], [2208,679], [3135,44], [3192,61], [3284,91], [3393,123], [3528,159], [3695,209], [3912,271]]
  court_size: [25, 20]
